version: 2
updates:
  - package-ecosystem: "docker-compose"
    directory: "/"  
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 5
    rebase-strategy: "auto"